### ISSUE TITLE
Fixed MultiSelect

### ISSUE THREAD

**Issue by nikitakarpinskiy** [Cado-Labs/sphere-ui#12]
If you have a small list. You'll see this:
![Снимок экрана 2021-11-23 в 16 36 29](https://user-images.githubusercontent.com/94894606/143034167-3754e212-aa2f-48ab-a01c-79dca4c7d8be.png)
I chose an item and i need close this list. But I don't have icon to close list.
for example basic MultiSelect from PrimeReact
![Снимок экрана 2021-11-23 в 16 40 59](https://user-images.githubusercontent.com/94894606/143034718-e45f3347-1407-4050-8627-5499249bda7e.png)

**Comment by nikitakarpinskiy** [comment]
I founded error “Encountered two children with the same key,` null` ”in MultiSelect in sphere-ui.

Since it was being finalized, with the renewal of the sphere, not all params fall there. For example itemTemplate and dataKey.
Because of this, when the list is created, it can't generate a key for each item.

**Comment by tysky** [comment]
We don't need to have a button for closing dropdown because clicking outside of the element does the same thing. `dataKey` property was added in #90,
