### ISSUE TITLE
Fixed tree DragDrop

### ISSUE THREAD

**Issue by nikitakarpinskiy** [Cado-Labs/sphere-ui#16]
You need to do a Drag Drop so that you can't put items into each other.
Add props, for example "needChildDragDrop" by default true and here add a check.

<img width="1207" alt="Снимок экрана 2021-12-23 в 12 36 29" src="https://user-images.githubusercontent.com/94894606/147226469-d20e5b2e-6119-4538-acb6-558cbfc7c5d5.png">

**Comment by elenik72** [comment]
This problem concerns Core changes to Prime, which is no longer our area of ​​responsibility. It is better to send this issue to https://github.com/primefaces/primereact/issues. We can complement and extend using their API
