### ISSUE TITLE
Update package publishing in CI

### ISSUE THREAD

**Issue by tysky** [Cado-Labs/sphere-ui#53]
Consider replacing the current workflow of package publishing with another one triggered by creating a new release in GitHub. 
Example of the workflow:
https://github.com/actions/starter-workflows/blob/4238ac653e5124c1e1f118cc0b0bd428b8973953/ci/npm-publish.yml

**Comment by elenik72** [comment]
Good decision. Worth trying. And remove the custom action at the same time) Cool 😎
